"""init schema

Revision ID: 78801c6dcb35
Revises: 
Create Date: 2025-09-02 20:50:23.360942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78801c6dcb35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad', sa.String(length=255), nullable=True),
    sa.Column('slug_autor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_autor'),
    sa.UniqueConstraint('slug_autor')
    )
    op.create_table('carreras',
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('nombre_carrera', sa.String(length=100), nullable=False),
    sa.Column('slug_carrera', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_carrera'),
    sa.UniqueConstraint('slug_carrera')
    )
    op.create_table('libros',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=100), nullable=False),
    sa.Column('anio_publicacion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('archivo_pdf', sa.String(length=200), nullable=False),
    sa.Column('slug_titulo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_libro'),
    sa.UniqueConstraint('slug_titulo')
    )
    op.create_table('libros_autores',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['autores.id_autor'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id_libro'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_libro', 'id_autor')
    )
    op.create_table('libros_carreras',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id_libro'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_libro', 'id_carrera')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=255), nullable=False),
    sa.Column('correo_institucional', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.UniqueConstraint('correo_institucional')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('libros_carreras')
    op.drop_table('libros_autores')
    op.drop_table('libros')
    op.drop_table('carreras')
    op.drop_table('autores')
    # ### end Alembic commands ###
