"""empty message

Revision ID: 86fd60f36d08
Revises: 2e12492b7549
Create Date: 2025-09-04 11:55:41.300015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fd60f36d08'
down_revision = '2e12492b7549'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=255), nullable=False),
    sa.Column('correo_institucional', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.UniqueConstraint('correo_institucional')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
