"""Renombrado slug_libro a slug_titulo

Revision ID: 93fe214a8251
Revises: fb7b37a00c9e
Create Date: 2025-11-11 19:29:06.971960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fe214a8251'
down_revision = 'fb7b37a00c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug_titulo', sa.String(length=300), nullable=False))
        batch_op.create_unique_constraint(None, ['slug_titulo'])
        batch_op.drop_column('slug_libro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug_libro', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug_titulo')

    # ### end Alembic commands ###
