"""Agregación de fecha creación y visualizaciones a modelo libros

Revision ID: a2d581511f73
Revises: 93fe214a8251
Create Date: 2025-11-29 00:56:18.365073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d581511f73'
down_revision = '93fe214a8251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visualizaciones', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('visualizaciones')

    # ### end Alembic commands ###
