"""Añadir portada a libros

Revision ID: a8fcad70790b
Revises: da379d7831f9
Create Date: 2025-11-10 18:50:26.044904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fcad70790b'
down_revision = 'da379d7831f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_portada', sa.String(length=255), nullable=True))
        batch_op.alter_column('archivo_pdf',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.alter_column('archivo_pdf',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('archivo_portada')

    # ### end Alembic commands ###
