"""empty message

Revision ID: eb87058f884d
Revises: bf4a3f46ac2c
Create Date: 2025-04-30 15:12:27.658204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb87058f884d'
down_revision = 'bf4a3f46ac2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('anio_publicacion',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('anio_publicacion',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
